name: Update Filesystem Index

on:
  push:
    paths:
      - 'filesystem/files/**'
      - '.github/workflows/indexer.yml'
      - 'filesystem/generate_filelist.py'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Indexer Script
      run: python filesystem/generate_filelist.py

    - name: Commit and Push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add filesystem/filelist.json
        # Only commit if there are changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update filesystem index" && git push)
